### ISSUE TITLE
Look at publish error: unexpected json error

### ISSUE THREAD

**Issue by andrewxhill** [textileio/storage-js#7]
dang, thought this was going to be a quick fix. but hit a snag running publish

https://github.com/textileio/storage-js/runs/3334114966?check_suite_focus=true

tried to copy this approach https://github.com/textileio/storage-js/commit/4eeb086d6db8ada4124764ec9f1a49ff24ff0b4d

ever hit this @carsonfarmer ?

**Comment by carsonfarmer** [comment]
Fixed with 68faa84d6266f045d4befa6abadb013e2dcf2292
